-- Country knowledge seed. Ids match world-atlas (Stage 2/3).
-- Run after schema.sql in the Supabase SQL editor.

insert into public.countries (
  id, name, iso_code, continent, capital, population, area, description, flag_url
) values
('004', 'Afghanistan', 'AF', 'Asia', 'Kabul', 43000000, 652230, 'A landlocked country in South-Central Asia, framed by the Hindu Kush and long caravan routes.', 'https://flagcdn.com/w160/af.png'),
('008', 'Albania', 'AL', 'Europe', 'Tirana', 2800000, 28748, 'A mountainous Balkan country on the Adriatic and Ionian seas.', 'https://flagcdn.com/w160/al.png'),
('010', 'Antarctica', 'AQ', 'Antarctica', null, 5000, 14200000, 'Earth''s southernmost continent, covered by ice and used mainly for science rather than settlement.', 'https://flagcdn.com/w160/aq.png'),
('012', 'Algeria', 'DZ', 'Africa', 'Algiers', 46000000, 2381741, 'Africa''s largest country, stretching from Mediterranean cities to the Sahara.', 'https://flagcdn.com/w160/dz.png'),
('024', 'Angola', 'AO', 'Africa', 'Luanda', 37000000, 1246700, 'A southwestern African country on the Atlantic, rich in oil, diamonds, and highland plateaus.', 'https://flagcdn.com/w160/ao.png'),
('031', 'Azerbaijan', 'AZ', 'Asia', 'Baku', 10400000, 86600, 'A Caucasus country on the Caspian Sea, where Europe and Asia meet.', 'https://flagcdn.com/w160/az.png'),
('032', 'Argentina', 'AR', 'South America', 'Buenos Aires', 46000000, 2780400, 'A long South American country from subtropical north to Andean west and Patagonian south.', 'https://flagcdn.com/w160/ar.png'),
('036', 'Australia', 'AU', 'Oceania', 'Canberra', 27000000, 7692024, 'A continent-country of deserts, reefs, and coastal cities in the Southern Hemisphere.', 'https://flagcdn.com/w160/au.png'),
('040', 'Austria', 'AT', 'Europe', 'Vienna', 9100000, 83871, 'An Alpine republic in Central Europe, historically a crossroads of the Danube basin.', 'https://flagcdn.com/w160/at.png'),
('044', 'Bahamas', 'BS', 'North America', 'Nassau', 410000, 13880, 'An island country of turquoise shallows in the Atlantic east of Florida.', 'https://flagcdn.com/w160/bs.png'),
('050', 'Bangladesh', 'BD', 'Asia', 'Dhaka', 173000000, 147570, 'A densely populated delta nation on the Bay of Bengal, shaped by the Ganges and Brahmaputra.', 'https://flagcdn.com/w160/bd.png'),
('051', 'Armenia', 'AM', 'Asia', 'Yerevan', 3000000, 29743, 'A highland country in the South Caucasus, one of the world''s oldest Christian states.', 'https://flagcdn.com/w160/am.png'),
('056', 'Belgium', 'BE', 'Europe', 'Brussels', 11700000, 30528, 'A lowland European country at the meeting of Latin and Germanic Europe.', 'https://flagcdn.com/w160/be.png'),
('064', 'Bhutan', 'BT', 'Asia', 'Thimphu', 780000, 38394, 'A Himalayan kingdom between India and China, known for high valleys and forests.', 'https://flagcdn.com/w160/bt.png'),
('068', 'Bolivia', 'BO', 'South America', 'Sucre', 12400000, 1098581, 'A landlocked Andean country of altiplano, rainforest, and the city of La Paz.', 'https://flagcdn.com/w160/bo.png'),
('070', 'Bosnia and Herz.', 'BA', 'Europe', 'Sarajevo', 3200000, 51209, 'A mountainous Balkan country of mixed cultural landscapes in southeast Europe.', 'https://flagcdn.com/w160/ba.png'),
('072', 'Botswana', 'BW', 'Africa', 'Gaborone', 2700000, 581730, 'A largely arid southern African country centered on the Kalahari and Okavango Delta.', 'https://flagcdn.com/w160/bw.png'),
('076', 'Brazil', 'BR', 'South America', 'Brasília', 216000000, 8515767, 'The largest country in South America, spanning Amazon rainforest, cerrado, and a long Atlantic coast.', 'https://flagcdn.com/w160/br.png'),
('084', 'Belize', 'BZ', 'North America', 'Belmopan', 410000, 22966, 'A small Central American country on the Caribbean, with reef, rainforest, and Maya sites.', 'https://flagcdn.com/w160/bz.png'),
('090', 'Solomon Is.', 'SB', 'Oceania', 'Honiara', 740000, 28896, 'A Melanesian island nation east of Papua New Guinea, scattered across the Coral Sea.', 'https://flagcdn.com/w160/sb.png'),
('096', 'Brunei', 'BN', 'Asia', 'Bandar Seri Begawan', 450000, 5765, 'A small Bornean sultanate on the South China Sea, largely covered by rainforest.', 'https://flagcdn.com/w160/bn.png'),
('100', 'Bulgaria', 'BG', 'Europe', 'Sofia', 6400000, 110879, 'A Balkan country on the Black Sea, between the Danube and the Rhodope mountains.', 'https://flagcdn.com/w160/bg.png'),
('104', 'Myanmar', 'MM', 'Asia', 'Naypyidaw', 54000000, 676578, 'A mainland Southeast Asian country along the Irrawaddy, between the Bay of Bengal and the hills of Yunnan.', 'https://flagcdn.com/w160/mm.png'),
('108', 'Burundi', 'BI', 'Africa', 'Gitega', 13000000, 27834, 'A compact Great Lakes country in East Africa, high and densely farmed.', 'https://flagcdn.com/w160/bi.png'),
('112', 'Belarus', 'BY', 'Europe', 'Minsk', 9200000, 207600, 'A landlocked East European country of forests, marshes, and glacial plains.', 'https://flagcdn.com/w160/by.png'),
('116', 'Cambodia', 'KH', 'Asia', 'Phnom Penh', 17000000, 181035, 'A mainland Southeast Asian country on the Mekong, home to Angkor and the Tonle Sap.', 'https://flagcdn.com/w160/kh.png'),
('120', 'Cameroon', 'CM', 'Africa', 'Yaoundé', 29000000, 475442, 'A Central African country from Gulf of Guinea rainforest to Sahelian north.', 'https://flagcdn.com/w160/cm.png'),
('124', 'Canada', 'CA', 'North America', 'Ottawa', 41000000, 9984670, 'The world''s second-largest country, stretching from Atlantic to Pacific and into the Arctic.', 'https://flagcdn.com/w160/ca.png'),
('140', 'Central African Rep.', 'CF', 'Africa', 'Bangui', 5800000, 622984, 'A landlocked country at the heart of Africa, covering savanna and rainforest basins.', 'https://flagcdn.com/w160/cf.png'),
('144', 'Sri Lanka', 'LK', 'Asia', 'Sri Jayawardenepura Kotte', 22000000, 65610, 'An island in the Indian Ocean, south of India, with highlands, tea country, and ancient cities.', 'https://flagcdn.com/w160/lk.png'),
('148', 'Chad', 'TD', 'Africa', 'N''Djamena', 18000000, 1284000, 'A landlocked Sahelian country from the Sahara to Lake Chad and southern savannas.', 'https://flagcdn.com/w160/td.png'),
('152', 'Chile', 'CL', 'South America', 'Santiago', 19600000, 756102, 'A narrow Andean country along the Pacific, from Atacama Desert to Patagonian fjords.', 'https://flagcdn.com/w160/cl.png'),
('156', 'China', 'CN', 'Asia', 'Beijing', 1412000000, 9596961, 'East Asia''s largest country, from Pacific megacities to the Tibetan Plateau and Gobi.', 'https://flagcdn.com/w160/cn.png'),
('158', 'Taiwan', 'TW', 'Asia', 'Taipei', 23400000, 36197, 'An island off China''s southeast coast, mountainous in the east and densely settled in the west.', 'https://flagcdn.com/w160/tw.png'),
('170', 'Colombia', 'CO', 'South America', 'Bogotá', 52000000, 1141748, 'A country of Andes, Amazon, and two coasts, on both the Pacific and the Caribbean.', 'https://flagcdn.com/w160/co.png'),
('178', 'Congo', 'CG', 'Africa', 'Brazzaville', 6100000, 342000, 'A Central African country on the Congo River, west of the Democratic Republic of the Congo.', 'https://flagcdn.com/w160/cg.png'),
('180', 'Dem. Rep. Congo', 'CD', 'Africa', 'Kinshasa', 102000000, 2344858, 'Africa''s second-largest country, spanning Congo Basin rainforest and mineral-rich highlands.', 'https://flagcdn.com/w160/cd.png'),
('188', 'Costa Rica', 'CR', 'North America', 'San José', 5200000, 51100, 'A Central American country between Caribbean and Pacific, known for volcanoes and rainforest.', 'https://flagcdn.com/w160/cr.png'),
('191', 'Croatia', 'HR', 'Europe', 'Zagreb', 3800000, 56594, 'A European country with a long Adriatic coastline of islands and limestone karst.', 'https://flagcdn.com/w160/hr.png'),
('192', 'Cuba', 'CU', 'North America', 'Havana', 11000000, 109884, 'The largest Caribbean island, lying at the mouth of the Gulf of Mexico.', 'https://flagcdn.com/w160/cu.png'),
('196', 'Cyprus', 'CY', 'Asia', 'Nicosia', 1300000, 9251, 'An eastern Mediterranean island at the meeting of Europe, Asia, and the Levant.', 'https://flagcdn.com/w160/cy.png'),
('203', 'Czechia', 'CZ', 'Europe', 'Prague', 10900000, 78867, 'A landlocked Central European country in the upper basins of the Elbe and Morava.', 'https://flagcdn.com/w160/cz.png'),
('204', 'Benin', 'BJ', 'Africa', 'Porto-Novo', 14000000, 114763, 'A West African country on the Bight of Benin, stretching north into the savanna.', 'https://flagcdn.com/w160/bj.png'),
('208', 'Denmark', 'DK', 'Europe', 'Copenhagen', 5900000, 43094, 'A Nordic country of Jutland and islands, linking the North Sea and the Baltic.', 'https://flagcdn.com/w160/dk.png'),
('214', 'Dominican Rep.', 'DO', 'North America', 'Santo Domingo', 11300000, 48671, 'The eastern part of Hispaniola, a Caribbean country of mountains and Atlantic beaches.', 'https://flagcdn.com/w160/do.png'),
('218', 'Ecuador', 'EC', 'South America', 'Quito', 18000000, 276841, 'An Andean country on the equator, including the Galápagos Islands in the Pacific.', 'https://flagcdn.com/w160/ec.png'),
('222', 'El Salvador', 'SV', 'North America', 'San Salvador', 6300000, 21041, 'The smallest mainland Central American country, on the Pacific volcanic chain.', 'https://flagcdn.com/w160/sv.png'),
('226', 'Eq. Guinea', 'GQ', 'Africa', 'Malabo', 1700000, 28051, 'A Central African country of a mainland region and volcanic islands in the Gulf of Guinea.', 'https://flagcdn.com/w160/gq.png'),
('231', 'Ethiopia', 'ET', 'Africa', 'Addis Ababa', 127000000, 1104300, 'A highland East African country, source of the Blue Nile and an ancient Horn of Africa state.', 'https://flagcdn.com/w160/et.png'),
('232', 'Eritrea', 'ER', 'Africa', 'Asmara', 3700000, 117600, 'A Red Sea country in the Horn of Africa, with highlands inland and a long desert coast.', 'https://flagcdn.com/w160/er.png'),
('233', 'Estonia', 'EE', 'Europe', 'Tallinn', 1400000, 45228, 'A Baltic country of forests and islands on the Gulf of Finland.', 'https://flagcdn.com/w160/ee.png'),
('238', 'Falkland Is.', 'FK', 'South America', 'Stanley', 3500, 12173, 'A South Atlantic archipelago east of southern Argentina, windswept and sparsely settled.', 'https://flagcdn.com/w160/fk.png'),
('242', 'Fiji', 'FJ', 'Oceania', 'Suva', 930000, 18272, 'A Melanesian island country in the South Pacific, of volcanic islands and coral reefs.', 'https://flagcdn.com/w160/fj.png'),
('246', 'Finland', 'FI', 'Europe', 'Helsinki', 5600000, 338145, 'A northern European country of lakes and forests, reaching into the Arctic.', 'https://flagcdn.com/w160/fi.png'),
('250', 'France', 'FR', 'Europe', 'Paris', 68000000, 551695, 'A Western European country from the Channel to the Mediterranean, with a wide overseas reach.', 'https://flagcdn.com/w160/fr.png'),
('260', 'Fr. S. Antarctic Lands', 'TF', 'Antarctica', 'Port-aux-Français', 200, 7747, 'French Southern and Antarctic lands, remote islands and ice in the southern Indian Ocean.', 'https://flagcdn.com/w160/tf.png'),
('262', 'Djibouti', 'DJ', 'Africa', 'Djibouti', 1100000, 23200, 'A small Horn of Africa country at the Bab el-Mandeb, where the Red Sea meets the Gulf of Aden.', 'https://flagcdn.com/w160/dj.png'),
('266', 'Gabon', 'GA', 'Africa', 'Libreville', 2400000, 267668, 'A Central African country on the Atlantic, largely covered by equatorial forest.', 'https://flagcdn.com/w160/ga.png'),
('268', 'Georgia', 'GE', 'Asia', 'Tbilisi', 3700000, 69700, 'A Caucasus country on the Black Sea, between the Greater and Lesser Caucasus ranges.', 'https://flagcdn.com/w160/ge.png'),
('270', 'Gambia', 'GM', 'Africa', 'Banjul', 2800000, 11295, 'West Africa''s smallest mainland country, following the Gambia River through Senegal.', 'https://flagcdn.com/w160/gm.png'),
('275', 'Palestine', 'PS', 'Asia', 'Ramallah', 5400000, 6020, 'A Levantine territory on the eastern Mediterranean, including the West Bank and Gaza Strip.', 'https://flagcdn.com/w160/ps.png'),
('276', 'Germany', 'DE', 'Europe', 'Berlin', 84000000, 357022, 'A Central European country from the North Sea and Baltic to the Alps.', 'https://flagcdn.com/w160/de.png'),
('288', 'Ghana', 'GH', 'Africa', 'Accra', 34000000, 238533, 'A West African country on the Gulf of Guinea, between rainforest coast and northern savanna.', 'https://flagcdn.com/w160/gh.png'),
('300', 'Greece', 'GR', 'Europe', 'Athens', 10400000, 131957, 'A southeastern European country of mountains and islands in the Aegean and Ionian seas.', 'https://flagcdn.com/w160/gr.png'),
('304', 'Greenland', 'GL', 'North America', 'Nuuk', 57000, 2166086, 'The world''s largest island, an autonomous Arctic territory of ice sheet and coastal settlements.', 'https://flagcdn.com/w160/gl.png'),
('320', 'Guatemala', 'GT', 'North America', 'Guatemala City', 18000000, 108889, 'A Central American country of highlands, volcanoes, and ancient Maya cities.', 'https://flagcdn.com/w160/gt.png'),
('324', 'Guinea', 'GN', 'Africa', 'Conakry', 14000000, 245857, 'A West African country on the Atlantic, source of the Niger, Senegal, and Gambia rivers.', 'https://flagcdn.com/w160/gn.png'),
('328', 'Guyana', 'GY', 'South America', 'Georgetown', 800000, 214969, 'A northern South American country on the Atlantic, of rainforest, rivers, and a low coastal plain.', 'https://flagcdn.com/w160/gy.png'),
('332', 'Haiti', 'HT', 'North America', 'Port-au-Prince', 11700000, 27750, 'The western third of Hispaniola, a mountainous Caribbean country facing the Windward Passage.', 'https://flagcdn.com/w160/ht.png'),
('340', 'Honduras', 'HN', 'North America', 'Tegucigalpa', 11000000, 112492, 'A Central American country between Caribbean and Pacific, with highlands and a Mosquito Coast.', 'https://flagcdn.com/w160/hn.png'),
('348', 'Hungary', 'HU', 'Europe', 'Budapest', 9600000, 93028, 'A landlocked Central European country in the Carpathian Basin, crossed by the Danube.', 'https://flagcdn.com/w160/hu.png'),
('352', 'Iceland', 'IS', 'Europe', 'Reykjavík', 390000, 103000, 'A volcanic North Atlantic island of glaciers, rift valleys, and sparsely populated interiors.', 'https://flagcdn.com/w160/is.png'),
('356', 'India', 'IN', 'Asia', 'New Delhi', 1429000000, 3287263, 'A vast South Asian country from the Himalaya to the Indian Ocean, of many climates and languages.', 'https://flagcdn.com/w160/in.png'),
('360', 'Indonesia', 'ID', 'Asia', 'Jakarta', 278000000, 1904569, 'The world''s largest archipelagic country, spanning the equator between Asia and Australia.', 'https://flagcdn.com/w160/id.png'),
('364', 'Iran', 'IR', 'Asia', 'Tehran', 89000000, 1648195, 'A highland country in Western Asia, between the Caspian Sea and the Persian Gulf.', 'https://flagcdn.com/w160/ir.png'),
('368', 'Iraq', 'IQ', 'Asia', 'Baghdad', 45000000, 438317, 'A Mesopotamian country of the Tigris and Euphrates, from mountains in the north to Gulf marshes.', 'https://flagcdn.com/w160/iq.png'),
('372', 'Ireland', 'IE', 'Europe', 'Dublin', 5300000, 70273, 'An island country in the North Atlantic, occupying most of the island of Ireland.', 'https://flagcdn.com/w160/ie.png'),
('376', 'Israel', 'IL', 'Asia', 'Jerusalem', 9800000, 22145, 'A Levantine country on the eastern Mediterranean, from coastal plain to the Jordan Rift.', 'https://flagcdn.com/w160/il.png'),
('380', 'Italy', 'IT', 'Europe', 'Rome', 59000000, 301340, 'A southern European peninsula in the Mediterranean, including the Alps, islands, and a long coastline.', 'https://flagcdn.com/w160/it.png'),
('384', 'Côte d''Ivoire', 'CI', 'Africa', 'Yamoussoukro', 29000000, 322463, 'A West African country on the Gulf of Guinea, from lagoon coast to northern savanna.', 'https://flagcdn.com/w160/ci.png'),
('388', 'Jamaica', 'JM', 'North America', 'Kingston', 2800000, 10991, 'A mountainous Caribbean island south of Cuba, in the heart of the Greater Antilles.', 'https://flagcdn.com/w160/jm.png'),
('392', 'Japan', 'JP', 'Asia', 'Tokyo', 124000000, 377975, 'An East Asian archipelago of volcanic islands along the Pacific Ring of Fire.', 'https://flagcdn.com/w160/jp.png'),
('398', 'Kazakhstan', 'KZ', 'Asia', 'Astana', 20000000, 2724900, 'The world''s largest landlocked country, of steppe and desert across Central Asia.', 'https://flagcdn.com/w160/kz.png'),
('400', 'Jordan', 'JO', 'Asia', 'Amman', 11300000, 89342, 'An Arab country east of the Jordan River, from highlands to the Dead Sea and Wadi Rum.', 'https://flagcdn.com/w160/jo.png'),
('404', 'Kenya', 'KE', 'Africa', 'Nairobi', 55000000, 580367, 'An East African country on the equator, from Indian Ocean coast to the Rift Valley and highlands.', 'https://flagcdn.com/w160/ke.png'),
('408', 'North Korea', 'KP', 'Asia', 'Pyongyang', 26000000, 120538, 'The northern part of the Korean Peninsula, mountainous and facing both Yellow Sea and Sea of Japan.', 'https://flagcdn.com/w160/kp.png'),
('410', 'South Korea', 'KR', 'Asia', 'Seoul', 52000000, 100210, 'The southern Korean Peninsula, a mountainous East Asian country with a densely settled west coast.', 'https://flagcdn.com/w160/kr.png'),
('414', 'Kuwait', 'KW', 'Asia', 'Kuwait City', 4300000, 17818, 'A small Arabian country at the head of the Persian Gulf.', 'https://flagcdn.com/w160/kw.png'),
('417', 'Kyrgyzstan', 'KG', 'Asia', 'Bishkek', 7000000, 199951, 'A mountainous Central Asian country of the Tien Shan, largely highland and pastoral.', 'https://flagcdn.com/w160/kg.png'),
('418', 'Laos', 'LA', 'Asia', 'Vientiane', 7600000, 236800, 'A landlocked Southeast Asian country along the Mekong, between Vietnam and Thailand.', 'https://flagcdn.com/w160/la.png'),
('422', 'Lebanon', 'LB', 'Asia', 'Beirut', 5500000, 10452, 'A small Levantine country on the eastern Mediterranean, of a narrow coast and Mount Lebanon.', 'https://flagcdn.com/w160/lb.png'),
('426', 'Lesotho', 'LS', 'Africa', 'Maseru', 2300000, 30355, 'A high-altitude kingdom entirely surrounded by South Africa, in the Drakensberg–Maloti ranges.', 'https://flagcdn.com/w160/ls.png'),
('428', 'Latvia', 'LV', 'Europe', 'Riga', 1800000, 64589, 'A Baltic country on the Gulf of Riga, of forests, lakes, and a low coastal plain.', 'https://flagcdn.com/w160/lv.png'),
('430', 'Liberia', 'LR', 'Africa', 'Monrovia', 5400000, 111369, 'A West African country on the Atlantic, with rainforest coast and inland plateaus.', 'https://flagcdn.com/w160/lr.png'),
('434', 'Libya', 'LY', 'Africa', 'Tripoli', 6900000, 1759540, 'A North African country on the Mediterranean, mostly Sahara beyond a thin coastal strip.', 'https://flagcdn.com/w160/ly.png'),
('440', 'Lithuania', 'LT', 'Europe', 'Vilnius', 2900000, 65300, 'A Baltic country on the southeastern shore of the Baltic Sea.', 'https://flagcdn.com/w160/lt.png'),
('442', 'Luxembourg', 'LU', 'Europe', 'Luxembourg', 660000, 2586, 'A small landlocked country in Western Europe, between Belgium, France, and Germany.', 'https://flagcdn.com/w160/lu.png'),
('450', 'Madagascar', 'MG', 'Africa', 'Antananarivo', 30000000, 587041, 'The world''s fourth-largest island, in the Indian Ocean, with unique wildlife and highland interiors.', 'https://flagcdn.com/w160/mg.png'),
('454', 'Malawi', 'MW', 'Africa', 'Lilongwe', 21000000, 118484, 'A landlocked East African country along Lake Malawi in the Great Rift Valley.', 'https://flagcdn.com/w160/mw.png'),
('458', 'Malaysia', 'MY', 'Asia', 'Kuala Lumpur', 34000000, 330803, 'A Southeast Asian country of Peninsular Malaysia and northern Borneo, largely tropical forest.', 'https://flagcdn.com/w160/my.png'),
('466', 'Mali', 'ML', 'Africa', 'Bamako', 23000000, 1240192, 'A landlocked Sahelian country along the Niger River, from Sahara to West African savanna.', 'https://flagcdn.com/w160/ml.png'),
('478', 'Mauritania', 'MR', 'Africa', 'Nouakchott', 4900000, 1030700, 'A largely Saharan country on the Atlantic, between Morocco and the Senegal River.', 'https://flagcdn.com/w160/mr.png'),
('484', 'Mexico', 'MX', 'North America', 'Mexico City', 128000000, 1964375, 'A North American country between the United States and Central America, of high plateaus and two coasts.', 'https://flagcdn.com/w160/mx.png'),
('496', 'Mongolia', 'MN', 'Asia', 'Ulaanbaatar', 3400000, 1564116, 'A landlocked East Asian country of steppe and Gobi, between Russia and China.', 'https://flagcdn.com/w160/mn.png'),
('498', 'Moldova', 'MD', 'Europe', 'Chișinău', 2500000, 33846, 'A landlocked East European country between Romania and Ukraine, in the Dniester basin.', 'https://flagcdn.com/w160/md.png'),
('499', 'Montenegro', 'ME', 'Europe', 'Podgorica', 620000, 13812, 'A small Balkan country of mountains and a short Adriatic coast.', 'https://flagcdn.com/w160/me.png'),
('504', 'Morocco', 'MA', 'Africa', 'Rabat', 38000000, 446550, 'A Northwest African country from Atlantic and Mediterranean coasts to Atlas and Sahara.', 'https://flagcdn.com/w160/ma.png'),
('508', 'Mozambique', 'MZ', 'Africa', 'Maputo', 34000000, 801590, 'A long southeastern African country on the Indian Ocean, crossed by the Zambezi.', 'https://flagcdn.com/w160/mz.png'),
('512', 'Oman', 'OM', 'Asia', 'Muscat', 5200000, 309500, 'An Arabian Peninsula country on the Gulf of Oman and Arabian Sea, of mountains and desert.', 'https://flagcdn.com/w160/om.png'),
('516', 'Namibia', 'NA', 'Africa', 'Windhoek', 2600000, 825615, 'A southwestern African country on the Atlantic, dominated by the Namib and Kalahari deserts.', 'https://flagcdn.com/w160/na.png'),
('524', 'Nepal', 'NP', 'Asia', 'Kathmandu', 31000000, 147181, 'A Himalayan country between India and China, including Earth''s highest peaks.', 'https://flagcdn.com/w160/np.png'),
('528', 'Netherlands', 'NL', 'Europe', 'Amsterdam', 18000000, 41543, 'A low-lying Western European country on the North Sea, much of it reclaimed from water.', 'https://flagcdn.com/w160/nl.png'),
('540', 'New Caledonia', 'NC', 'Oceania', 'Nouméa', 290000, 18575, 'A French Pacific collectivity east of Australia, of a long main island and surrounding reefs.', 'https://flagcdn.com/w160/nc.png'),
('548', 'Vanuatu', 'VU', 'Oceania', 'Port-Vila', 330000, 12189, 'A volcanic Melanesian archipelago in the South Pacific.', 'https://flagcdn.com/w160/vu.png'),
('554', 'New Zealand', 'NZ', 'Oceania', 'Wellington', 5200000, 270467, 'A South Pacific country of two main islands, along a tectonic boundary of mountains and fjords.', 'https://flagcdn.com/w160/nz.png'),
('558', 'Nicaragua', 'NI', 'North America', 'Managua', 7000000, 130373, 'A Central American country of lakes, volcanoes, and coasts on both Caribbean and Pacific.', 'https://flagcdn.com/w160/ni.png'),
('562', 'Niger', 'NE', 'Africa', 'Niamey', 27000000, 1267000, 'A landlocked Sahelian country named for the Niger River, mostly Sahara in the north.', 'https://flagcdn.com/w160/ne.png'),
('566', 'Nigeria', 'NG', 'Africa', 'Abuja', 227000000, 923768, 'Africa''s most populous country, on the Gulf of Guinea, from Niger Delta to Sahelian north.', 'https://flagcdn.com/w160/ng.png'),
('578', 'Norway', 'NO', 'Europe', 'Oslo', 5500000, 323802, 'A Nordic country of mountains and fjords along the North Atlantic and Arctic Ocean.', 'https://flagcdn.com/w160/no.png'),
('586', 'Pakistan', 'PK', 'Asia', 'Islamabad', 240000000, 881913, 'A South Asian country from Arabian Sea coast to the high Karakoram.', 'https://flagcdn.com/w160/pk.png'),
('591', 'Panama', 'PA', 'North America', 'Panama City', 4500000, 75417, 'The isthmus linking North and South America, crossed by the Panama Canal.', 'https://flagcdn.com/w160/pa.png'),
('598', 'Papua New Guinea', 'PG', 'Oceania', 'Port Moresby', 10300000, 462840, 'An Oceanian country occupying the eastern half of New Guinea and many nearby islands.', 'https://flagcdn.com/w160/pg.png'),
('600', 'Paraguay', 'PY', 'South America', 'Asunción', 6900000, 406752, 'A landlocked South American country on the Paraguay River, of Chaco and eastern farmland.', 'https://flagcdn.com/w160/py.png'),
('604', 'Peru', 'PE', 'South America', 'Lima', 34000000, 1285216, 'An Andean country on the Pacific, from coastal desert to Amazon lowlands.', 'https://flagcdn.com/w160/pe.png'),
('608', 'Philippines', 'PH', 'Asia', 'Manila', 117000000, 300000, 'A large island country in Southeast Asia, between the South China Sea and the Pacific.', 'https://flagcdn.com/w160/ph.png'),
('616', 'Poland', 'PL', 'Europe', 'Warsaw', 38000000, 312696, 'A Central European country on the Baltic, of plains, lakes, and southern uplands.', 'https://flagcdn.com/w160/pl.png'),
('620', 'Portugal', 'PT', 'Europe', 'Lisbon', 10000000, 92212, 'Western Europe''s Atlantic edge, on the Iberian Peninsula, including the Azores and Madeira.', 'https://flagcdn.com/w160/pt.png'),
('624', 'Guinea-Bissau', 'GW', 'Africa', 'Bissau', 2100000, 36125, 'A small West African country on the Atlantic, of estuaries and the Bijagós islands.', 'https://flagcdn.com/w160/gw.png'),
('626', 'Timor-Leste', 'TL', 'Asia', 'Dili', 1400000, 14874, 'An island country in the eastern Lesser Sundas, north of Australia.', 'https://flagcdn.com/w160/tl.png'),
('630', 'Puerto Rico', 'PR', 'North America', 'San Juan', 3200000, 9104, 'A Caribbean island east of Hispaniola, an unincorporated U.S. territory.', 'https://flagcdn.com/w160/pr.png'),
('634', 'Qatar', 'QA', 'Asia', 'Doha', 2700000, 11586, 'A small peninsula country on the Persian Gulf, mostly arid limestone desert.', 'https://flagcdn.com/w160/qa.png'),
('642', 'Romania', 'RO', 'Europe', 'Bucharest', 19000000, 238391, 'A southeastern European country of the Carpathians, Danube, and Black Sea coast.', 'https://flagcdn.com/w160/ro.png'),
('643', 'Russia', 'RU', 'Europe', 'Moscow', 144000000, 17098242, 'The world''s largest country, spanning Eastern Europe and northern Asia to the Pacific.', 'https://flagcdn.com/w160/ru.png'),
('646', 'Rwanda', 'RW', 'Africa', 'Kigali', 14000000, 26338, 'A densely populated Great Lakes country of a thousand hills in East Africa.', 'https://flagcdn.com/w160/rw.png'),
('682', 'Saudi Arabia', 'SA', 'Asia', 'Riyadh', 37000000, 2149690, 'The largest Arabian Peninsula country, of desert interior and Red Sea and Gulf coasts.', 'https://flagcdn.com/w160/sa.png'),
('686', 'Senegal', 'SN', 'Africa', 'Dakar', 18000000, 196722, 'A West African country on the Atlantic, at the westernmost point of mainland Africa.', 'https://flagcdn.com/w160/sn.png'),
('688', 'Serbia', 'RS', 'Europe', 'Belgrade', 6600000, 77474, 'A landlocked Balkan country on the Danube, in the western Balkans.', 'https://flagcdn.com/w160/rs.png'),
('694', 'Sierra Leone', 'SL', 'Africa', 'Freetown', 8900000, 71740, 'A West African country on the Atlantic, of peninsula, rainforest, and inland plateau.', 'https://flagcdn.com/w160/sl.png'),
('703', 'Slovakia', 'SK', 'Europe', 'Bratislava', 5400000, 49035, 'A landlocked Central European country along the Carpathians and the Danube.', 'https://flagcdn.com/w160/sk.png'),
('704', 'Vietnam', 'VN', 'Asia', 'Hanoi', 99000000, 331212, 'A long Southeast Asian country along the South China Sea, from Red River to Mekong Delta.', 'https://flagcdn.com/w160/vn.png'),
('705', 'Slovenia', 'SI', 'Europe', 'Ljubljana', 2100000, 20273, 'A small Alpine-Adriatic country between the Alps, Pannonian Basin, and a short coast.', 'https://flagcdn.com/w160/si.png'),
('706', 'Somalia', 'SO', 'Africa', 'Mogadishu', 18000000, 637657, 'A Horn of Africa country with Africa''s longest coastline, on the Gulf of Aden and Indian Ocean.', 'https://flagcdn.com/w160/so.png'),
('710', 'South Africa', 'ZA', 'Africa', 'Pretoria', 63000000, 1221037, 'A southern African country on two oceans, of highveld, cape, and mineral-rich interior.', 'https://flagcdn.com/w160/za.png'),
('716', 'Zimbabwe', 'ZW', 'Africa', 'Harare', 17000000, 390757, 'A landlocked southern African country on a high plateau between the Zambezi and Limpopo.', 'https://flagcdn.com/w160/zw.png'),
('724', 'Spain', 'ES', 'Europe', 'Madrid', 48000000, 505990, 'A southwestern European country on the Iberian Peninsula, with Mediterranean and Atlantic coasts.', 'https://flagcdn.com/w160/es.png'),
('728', 'S. Sudan', 'SS', 'Africa', 'Juba', 11000000, 644329, 'A landlocked East African country on the White Nile, of wetlands, savanna, and highland edges.', 'https://flagcdn.com/w160/ss.png'),
('729', 'Sudan', 'SD', 'Africa', 'Khartoum', 49000000, 1861484, 'A northeastern African country at the Nile''s confluence, from Sahara to Sahel.', 'https://flagcdn.com/w160/sd.png'),
('732', 'W. Sahara', 'EH', 'Africa', 'Laayoune', 580000, 266000, 'A sparsely populated Atlantic-Saharan territory on Africa''s northwest coast.', 'https://flagcdn.com/w160/eh.png'),
('740', 'Suriname', 'SR', 'South America', 'Paramaribo', 620000, 163820, 'A small northern South American country on the Atlantic, mostly rainforest inland.', 'https://flagcdn.com/w160/sr.png'),
('748', 'eSwatini', 'SZ', 'Africa', 'Mbabane', 1200000, 17364, 'A small landlocked kingdom in southern Africa, between Mozambique and South Africa.', 'https://flagcdn.com/w160/sz.png'),
('752', 'Sweden', 'SE', 'Europe', 'Stockholm', 10600000, 450295, 'A long Nordic country of forests and lakes, from the Baltic to the Scandinavian mountains.', 'https://flagcdn.com/w160/se.png'),
('756', 'Switzerland', 'CH', 'Europe', 'Bern', 8900000, 41284, 'A landlocked Alpine country at the watershed of Rhine, Rhône, and Po.', 'https://flagcdn.com/w160/ch.png'),
('760', 'Syria', 'SY', 'Asia', 'Damascus', 23000000, 185180, 'A Levantine country from Mediterranean coast to Euphrates steppe and desert.', 'https://flagcdn.com/w160/sy.png'),
('762', 'Tajikistan', 'TJ', 'Asia', 'Dushanbe', 10000000, 143100, 'A mountainous Central Asian country of the Pamirs, largely highland and river valleys.', 'https://flagcdn.com/w160/tj.png'),
('764', 'Thailand', 'TH', 'Asia', 'Bangkok', 72000000, 513120, 'A mainland Southeast Asian country of Chao Phraya plains, Malay Peninsula, and highlands.', 'https://flagcdn.com/w160/th.png'),
('768', 'Togo', 'TG', 'Africa', 'Lomé', 9100000, 56785, 'A narrow West African country from Gulf of Guinea coast to northern savanna.', 'https://flagcdn.com/w160/tg.png'),
('780', 'Trinidad and Tobago', 'TT', 'North America', 'Port of Spain', 1500000, 5130, 'A two-island country at the southern end of the Caribbean, just off Venezuela.', 'https://flagcdn.com/w160/tt.png'),
('784', 'United Arab Emirates', 'AE', 'Asia', 'Abu Dhabi', 9500000, 83600, 'A federation of emirates on the Persian Gulf, of desert, coast, and modern port cities.', 'https://flagcdn.com/w160/ae.png'),
('788', 'Tunisia', 'TN', 'Africa', 'Tunis', 12000000, 163610, 'A North African country on the Mediterranean, from Tell Atlas to Sahara.', 'https://flagcdn.com/w160/tn.png'),
('792', 'Turkey', 'TR', 'Asia', 'Ankara', 85000000, 783562, 'A transcontinental country of Anatolia and a small European Thrace, between seas and high plateaus.', 'https://flagcdn.com/w160/tr.png'),
('795', 'Turkmenistan', 'TM', 'Asia', 'Ashgabat', 6500000, 488100, 'A Central Asian country of the Karakum Desert, along the Caspian and Iran''s Kopet Dag.', 'https://flagcdn.com/w160/tm.png'),
('800', 'Uganda', 'UG', 'Africa', 'Kampala', 49000000, 241038, 'An East African Great Lakes country, source region of the White Nile.', 'https://flagcdn.com/w160/ug.png'),
('804', 'Ukraine', 'UA', 'Europe', 'Kyiv', 38000000, 603500, 'A large East European country on the Black Sea, of steppe, forest, and the Dnipro basin.', 'https://flagcdn.com/w160/ua.png'),
('807', 'Macedonia', 'MK', 'Europe', 'Skopje', 1800000, 25713, 'A landlocked Balkan country in the Vardar valley, often known as North Macedonia.', 'https://flagcdn.com/w160/mk.png'),
('818', 'Egypt', 'EG', 'Africa', 'Cairo', 114000000, 1002450, 'A northeastern African country along the Nile, from Mediterranean coast to desert and Red Sea.', 'https://flagcdn.com/w160/eg.png'),
('826', 'United Kingdom', 'GB', 'Europe', 'London', 68000000, 243610, 'An island country in northwest Europe, of Great Britain, Northern Ireland, and surrounding seas.', 'https://flagcdn.com/w160/gb.png'),
('834', 'Tanzania', 'TZ', 'Africa', 'Dodoma', 67000000, 947303, 'An East African country on the Indian Ocean, including Kilimanjaro, Zanzibar, and vast savannas.', 'https://flagcdn.com/w160/tz.png'),
('840', 'United States of America', 'US', 'North America', 'Washington, D.C.', 340000000, 9833517, 'A large North American country from Atlantic to Pacific, with Alaska and Pacific islands.', 'https://flagcdn.com/w160/us.png'),
('854', 'Burkina Faso', 'BF', 'Africa', 'Ouagadougou', 23000000, 272967, 'A landlocked West African country on the savanna, in the upper Volta basin.', 'https://flagcdn.com/w160/bf.png'),
('858', 'Uruguay', 'UY', 'South America', 'Montevideo', 3400000, 176215, 'A small South American country on the Atlantic and Río de la Plata, of rolling grassland.', 'https://flagcdn.com/w160/uy.png'),
('860', 'Uzbekistan', 'UZ', 'Asia', 'Tashkent', 36000000, 448978, 'A double-landlocked Central Asian country of deserts, oases, and historic Silk Road cities.', 'https://flagcdn.com/w160/uz.png'),
('862', 'Venezuela', 'VE', 'South America', 'Caracas', 29000000, 912050, 'A northern South American country on the Caribbean, of Andes, llanos, and Guiana Highlands.', 'https://flagcdn.com/w160/ve.png'),
('887', 'Yemen', 'YE', 'Asia', 'Sana''a', 34000000, 527968, 'A southern Arabian country on the Red Sea and Gulf of Aden, of highlands and desert.', 'https://flagcdn.com/w160/ye.png'),
('894', 'Zambia', 'ZM', 'Africa', 'Lusaka', 21000000, 752612, 'A landlocked southern African plateau country, crossed by the Zambezi.', 'https://flagcdn.com/w160/zm.png'),
('name:Kosovo', 'Kosovo', 'XK', 'Europe', 'Pristina', 1800000, 10887, 'A landlocked Balkan country in the western Balkans, of high plains and surrounding mountains.', 'https://flagcdn.com/w160/xk.png'),
('name:Somaliland', 'Somaliland', null, 'Africa', 'Hargeisa', 5700000, 176120, 'A self-declared state in the Horn of Africa on the Gulf of Aden, with Hargeisa as its main city.', null),
('name:N. Cyprus', 'N. Cyprus', null, 'Asia', 'North Nicosia', 380000, 3355, 'The northern part of Cyprus, a Mediterranean territory with a long coast on the north of the island.', null)
on conflict (id) do update set
  name = excluded.name,
  iso_code = excluded.iso_code,
  continent = excluded.continent,
  capital = excluded.capital,
  population = excluded.population,
  area = excluded.area,
  description = excluded.description,
  flag_url = excluded.flag_url;
